# fly.toml app configuration file generated for worldchat on 2023-07-23T01:03:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "worldchat"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 8080
    handlers = ["http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
